export const GET_USER_REGISTER = "GET_USER_REGISTER";
export const GET_USER_LOGIN = "GET_USER_LOGIN";
export const GET_AUTHORIZATION = "GET_AUTHORIZATION";
export const GET_DATA_SPEAKERS = "GET_DATA_SPEAKERS";
export const GET_SPEAKERS_DETAILS = "GET_SPEAKERS_DETAILS";
export const GET_FACEBOOK = "GET_FACEBOOK";
export const GET_CONTACT_US = "GET_CONTACT_US";
export const GET_TRANSACTION_SPEAKER = "GET_TRANSACTION_SPEAKER"
export const GET_TRANSACTION_AUDIENCE = "GET_TRANSACTION_AUDIENCE"
export const GET_TRANSACTION_DETAIL = "GET_TRANSACTION_DETAIL"
export const GET_SPEAKERS_BY_NAME = "GET_SPEAKERS_BY_NAME";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_SPEAKERS_BY_LOCATION = "GET_SPEAKERS_BY_LOCATION";

